//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEWSP_v2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CEWSP_v2.Properties.MainWindowResources", typeof(MainWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++.
        /// </summary>
        public static string BtnCpp {
            get {
                return ResourceManager.GetString("BtnCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last used.
        /// </summary>
        public static string BtnLastUsed {
            get {
                return ResourceManager.GetString("BtnLastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lua.
        /// </summary>
        public static string BtnLua {
            get {
                return ResourceManager.GetString("BtnLua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string GroubEditor {
            get {
                return ResourceManager.GetString("GroubEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string GroupCode {
            get {
                return ResourceManager.GetString("GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string GroupGame {
            get {
                return ResourceManager.GetString("GroupGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string GroupProgram {
            get {
                return ResourceManager.GetString("GroupProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commandline:.
        /// </summary>
        public static string LblCommandline {
            get {
                return ResourceManager.GetString("LblCommandline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32bit Editor.
        /// </summary>
        public static string LblEditor32Bit {
            get {
                return ResourceManager.GetString("LblEditor32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64bit Editor.
        /// </summary>
        public static string LblEditor64Bit {
            get {
                return ResourceManager.GetString("LblEditor64Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string TabCreate {
            get {
                return ResourceManager.GetString("TabCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy.
        /// </summary>
        public static string TabDeploy {
            get {
                return ResourceManager.GetString("TabDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string TabManage {
            get {
                return ResourceManager.GetString("TabManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string TabWork {
            get {
                return ResourceManager.GetString("TabWork", resourceCulture);
            }
        }
    }
}
