//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEWSP_v2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Welcome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Welcome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CEWSP_v2.Properties.Welcome", typeof(Welcome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show again. Load last active project on startup.
        /// </summary>
        public static string ChckDontShowWelcome {
            get {
                return ResourceManager.GetString("ChckDontShowWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string LblProjects {
            get {
                return ResourceManager.GetString("LblProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears you want to close the welcome window while there are no projects to be loaded. CEWSP needs a project to work and thus will close without any projects to be loaded. Do you still wish to close the application?.
        /// </summary>
        public static string MsgCloseWelcomeWithoutProjects {
            get {
                return ResourceManager.GetString("MsgCloseWelcomeWithoutProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter projects.
        /// </summary>
        public static string MsgFilterProjects {
            get {
                return ResourceManager.GetString("MsgFilterProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no existing projects found, please create a new one.
        /// </summary>
        public static string MsgNoProjectCreateNew {
            get {
                return ResourceManager.GetString("MsgNoProjectCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to CEWSP. Please choose a project to load or create a new one..
        /// </summary>
        public static string MsgWelcomeToCEWSP {
            get {
                return ResourceManager.GetString("MsgWelcomeToCEWSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to clear the filter text box.
        /// </summary>
        public static string TipClearFilter {
            get {
                return ResourceManager.GetString("TipClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new project.
        /// </summary>
        public static string TipCreate {
            get {
                return ResourceManager.GetString("TipCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEWSP needs at least one project to work with.
        /// </summary>
        public static string TipCreateNeedForProject {
            get {
                return ResourceManager.GetString("TipCreateNeedForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The welcome window can be reenabled throught the application settings.
        /// </summary>
        public static string TipDontShowCheckBox {
            get {
                return ResourceManager.GetString("TipDontShowCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot check this box if there were no projects found.
        /// </summary>
        public static string TipDontShowCheckBoxNoProjects {
            get {
                return ResourceManager.GetString("TipDontShowCheckBoxNoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exits the application.
        /// </summary>
        public static string TipExit {
            get {
                return ResourceManager.GetString("TipExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of the project you are looking for.
        /// </summary>
        public static string TipFilterProjects {
            get {
                return ResourceManager.GetString("TipFilterProjects", resourceCulture);
            }
        }
    }
}
