//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEWSP_Backend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateNewProject {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateNewProject() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CEWSP_Backend.Properties.CreateNewProject", typeof(CreateNewProject).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure template.
        /// </summary>
        public static string BtnConfigTemplate {
            get {
                return ResourceManager.GetString("BtnConfigTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No template.
        /// </summary>
        public static string DefaultTemplateName {
            get {
                return ResourceManager.GetString("DefaultTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a game folder name.
        /// </summary>
        public static string LblCEGame {
            get {
                return ResourceManager.GetString("LblCEGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the path to the CE editor executable..
        /// </summary>
        public static string LblCERoot {
            get {
                return ResourceManager.GetString("LblCERoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name:.
        /// </summary>
        public static string LblProjectName {
            get {
                return ResourceManager.GetString("LblProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a template (press &quot;Configure template&quot; to customize it).
        /// </summary>
        public static string LblTemplate {
            get {
                return ResourceManager.GetString("LblTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template description.
        /// </summary>
        public static string LblTemplateDesc {
            get {
                return ResourceManager.GetString("LblTemplateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your input contains errors, please fix them first (warnings may be ignored)..
        /// </summary>
        public static string NoCreateSolveIssues {
            get {
                return ResourceManager.GetString("NoCreateSolveIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An image to identify this project..
        /// </summary>
        public static string TipImage {
            get {
                return ResourceManager.GetString("TipImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the image click on it..
        /// </summary>
        public static string TipImageClickToBrowse {
            get {
                return ResourceManager.GetString("TipImageClickToBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rightclick and choose reset to reset the image to the default image.
        /// </summary>
        public static string TipImageRightReset {
            get {
                return ResourceManager.GetString("TipImageRightReset", resourceCulture);
            }
        }
    }
}
