//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEWSP_Backend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsDesc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsDesc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CEWSP_Backend.Properties.SettingsDesc", typeof(SettingsDesc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the Sandbox editor.
        /// </summary>
        public static string DescCEEditorRoot {
            get {
                return ResourceManager.GetString("DescCEEditorRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last used commandline arguments for the 64bit editor.
        /// </summary>
        public static string DescLastUsedEd64CommandLine {
            get {
                return ResourceManager.GetString("DescLastUsedEd64CommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project that was active when CEWSP was closed.
        /// </summary>
        public static string DescLastUsedProject {
            get {
                return ResourceManager.GetString("DescLastUsedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root directory in which LY was installed (contains &apos;dev&apos;).
        /// </summary>
        public static string DescLYRoot {
            get {
                return ResourceManager.GetString("DescLYRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root directory of the CE installation used for this project.
        /// </summary>
        public static string DescProjCERoot {
            get {
                return ResourceManager.GetString("DescProjCERoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root directory of the game folder used for this project.
        /// </summary>
        public static string DescProjGameFolder {
            get {
                return ResourceManager.GetString("DescProjGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the image associated with this project.
        /// </summary>
        public static string DescProjImage {
            get {
                return ResourceManager.GetString("DescProjImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of this project.
        /// </summary>
        public static string DescProjName {
            get {
                return ResourceManager.GetString("DescProjName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the welcome window be shown on startup.
        /// </summary>
        public static string DescShowWelcomeWindow {
            get {
                return ResourceManager.GetString("DescShowWelcomeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String indicating which Visual Studio version is used (either vs120 or vs140).
        /// </summary>
        public static string DescVisualSuffix {
            get {
                return ResourceManager.GetString("DescVisualSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox editor location.
        /// </summary>
        public static string HumCEEditorRoot {
            get {
                return ResourceManager.GetString("HumCEEditorRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last used editor 64bit commandline.
        /// </summary>
        public static string HumLastUsedEd64CommandLine {
            get {
                return ResourceManager.GetString("HumLastUsedEd64CommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last active project.
        /// </summary>
        public static string HumLastUsedProject {
            get {
                return ResourceManager.GetString("HumLastUsedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LY installation directory.
        /// </summary>
        public static string HumLYRoot {
            get {
                return ResourceManager.GetString("HumLYRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the Bin64\Editor.exe file of t.
        /// </summary>
        public static string HumProCERoot {
            get {
                return ResourceManager.GetString("HumProCERoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE Root installtion.
        /// </summary>
        public static string HumProjCERoot {
            get {
                return ResourceManager.GetString("HumProjCERoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game folder path.
        /// </summary>
        public static string HumProjGameFolder {
            get {
                return ResourceManager.GetString("HumProjGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project image path.
        /// </summary>
        public static string HumProjImage {
            get {
                return ResourceManager.GetString("HumProjImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string HumProjName {
            get {
                return ResourceManager.GetString("HumProjName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show welcome window on startup.
        /// </summary>
        public static string HumShowWelcomeWindow {
            get {
                return ResourceManager.GetString("HumShowWelcomeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio suffix.
        /// </summary>
        public static string HumVisualSuffix {
            get {
                return ResourceManager.GetString("HumVisualSuffix", resourceCulture);
            }
        }
    }
}
